package Vista;

import java.awt.BorderLayout;

/**
 *
 * @author Usuario
 */
public class Pantalla extends javax.swing.JFrame {

    /**
     * Creates new form Pantalla
     */
    public Pantalla() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        Menu = new javax.swing.JPanel();
        btn_baixa_curs = new javax.swing.JButton();
        btn_mat_estudiant = new javax.swing.JButton();
        btn_cursos = new javax.swing.JButton();
        btn_estudiants = new javax.swing.JButton();
        btn_baixa_assig = new javax.swing.JButton();
        btn_alta_curs = new javax.swing.JButton();
        btn_assignatures = new javax.swing.JButton();
        Header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Menu.setBackground(new java.awt.Color(13, 71, 161));

        btn_baixa_curs.setBackground(new java.awt.Color(18, 90, 173));
        btn_baixa_curs.setForeground(new java.awt.Color(255, 255, 255));
        btn_baixa_curs.setText("BAIXA CURS");
        btn_baixa_curs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_baixa_cursActionPerformed(evt);
            }
        });

        btn_mat_estudiant.setBackground(new java.awt.Color(18, 90, 173));
        btn_mat_estudiant.setForeground(new java.awt.Color(255, 255, 255));
        btn_mat_estudiant.setText("MATRICULAR ESTUDIANT");
        btn_mat_estudiant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mat_estudiantActionPerformed(evt);
            }
        });

        btn_cursos.setBackground(new java.awt.Color(18, 90, 173));
        btn_cursos.setForeground(new java.awt.Color(255, 255, 255));
        btn_cursos.setText("CURSOS");
        btn_cursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cursosActionPerformed(evt);
            }
        });

        btn_estudiants.setBackground(new java.awt.Color(18, 90, 173));
        btn_estudiants.setForeground(new java.awt.Color(255, 255, 255));
        btn_estudiants.setText("ESTUDIANTS");
        btn_estudiants.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_estudiantsActionPerformed(evt);
            }
        });

        btn_baixa_assig.setBackground(new java.awt.Color(18, 90, 173));
        btn_baixa_assig.setForeground(new java.awt.Color(255, 255, 255));
        btn_baixa_assig.setText("BAIXA ASSIGNATURA");
        btn_baixa_assig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_baixa_assigActionPerformed(evt);
            }
        });

        btn_alta_curs.setBackground(new java.awt.Color(18, 90, 173));
        btn_alta_curs.setForeground(new java.awt.Color(255, 255, 255));
        btn_alta_curs.setText("ALTA CURS");
        btn_alta_curs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_alta_cursActionPerformed(evt);
            }
        });

        btn_assignatures.setBackground(new java.awt.Color(18, 90, 173));
        btn_assignatures.setForeground(new java.awt.Color(255, 255, 255));
        btn_assignatures.setText("ASSIGNATURES");
        btn_assignatures.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_assignaturesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_mat_estudiant, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                    .addComponent(btn_alta_curs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_baixa_curs, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_baixa_assig, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_cursos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_assignatures, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_estudiants, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(btn_alta_curs, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_mat_estudiant, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_baixa_curs, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_baixa_assig, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101)
                .addComponent(btn_cursos, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_assignatures, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_estudiants, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        Background.add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 610));
        Menu.getAccessibleContext().setAccessibleName("");
        Menu.getAccessibleContext().setAccessibleDescription("");

        Header.setBackground(new java.awt.Color(13, 71, 161));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Algorismia i Estructura de Dades I");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Gestor Activitats Col·legi");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(268, Short.MAX_VALUE))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(46, 46, 46))
        );

        Background.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 600, 110));

        Content.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout ContentLayout = new javax.swing.GroupLayout(Content);
        Content.setLayout(ContentLayout);
        ContentLayout.setHorizontalGroup(
            ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );
        ContentLayout.setVerticalGroup(
            ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        Background.add(Content, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 590, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_alta_cursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_alta_cursActionPerformed
        alta_curs Jpanel_altaCurs = new alta_curs();
        Jpanel_altaCurs.setSize(590, 500);
        Jpanel_altaCurs.setLocation(0,0);
        
        Content.removeAll();
        Content.add(Jpanel_altaCurs,BorderLayout.CENTER);
        Content.revalidate();
        Content.repaint();
        
    }//GEN-LAST:event_btn_alta_cursActionPerformed

    private void btn_estudiantsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_estudiantsActionPerformed
        estudiants Jpanel_est = new estudiants();
        Jpanel_est.setSize(590, 500);
        Jpanel_est.setLocation(0,0);
        
        Content.removeAll();
        Content.add(Jpanel_est,BorderLayout.CENTER);
        Content.revalidate();
        Content.repaint();
    }//GEN-LAST:event_btn_estudiantsActionPerformed

    private void btn_baixa_assigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_baixa_assigActionPerformed
        baixa_assig Jpanel_baixaAss = new baixa_assig();
        Jpanel_baixaAss.setSize(590, 500);
        Jpanel_baixaAss.setLocation(0,0);
        
        Content.removeAll();
        Content.add(Jpanel_baixaAss,BorderLayout.CENTER);
        Content.revalidate();
        Content.repaint();
    }//GEN-LAST:event_btn_baixa_assigActionPerformed

    private void btn_cursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cursosActionPerformed
        cursos Jpanel_cursos = new cursos();
        Jpanel_cursos.setSize(590, 500);
        Jpanel_cursos.setLocation(0,0);
        
        Content.removeAll();
        Content.add(Jpanel_cursos,BorderLayout.CENTER);
        Content.revalidate();
        Content.repaint();
    }//GEN-LAST:event_btn_cursosActionPerformed

    private void btn_baixa_cursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_baixa_cursActionPerformed
        baixa_curs Jpanel_baixaCurs = new baixa_curs();
        Jpanel_baixaCurs.setSize(590, 500);
        Jpanel_baixaCurs.setLocation(0,0);
        
        Content.removeAll();
        Content.add(Jpanel_baixaCurs,BorderLayout.CENTER);
        Content.revalidate();
        Content.repaint();
    }//GEN-LAST:event_btn_baixa_cursActionPerformed

    private void btn_mat_estudiantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mat_estudiantActionPerformed
        mat_estudiant Jpanel_matEst = new mat_estudiant();
        Jpanel_matEst.setSize(590, 500);
        Jpanel_matEst.setLocation(0,0);
        
        Content.removeAll();
        Content.add(Jpanel_matEst,BorderLayout.CENTER);
        Content.revalidate();
        Content.repaint();
    }//GEN-LAST:event_btn_mat_estudiantActionPerformed

    private void btn_assignaturesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_assignaturesActionPerformed
        assignatures Jpanel_ass = new assignatures();
        Jpanel_ass.setSize(590, 500);
        Jpanel_ass.setLocation(0,0);
        
        Content.removeAll();
        Content.add(Jpanel_ass,BorderLayout.CENTER);
        Content.revalidate();
        Content.repaint();
    }//GEN-LAST:event_btn_assignaturesActionPerformed

    
    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JPanel Content;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Menu;
    private javax.swing.JButton btn_alta_curs;
    private javax.swing.JButton btn_assignatures;
    private javax.swing.JButton btn_baixa_assig;
    private javax.swing.JButton btn_baixa_curs;
    private javax.swing.JButton btn_cursos;
    private javax.swing.JButton btn_estudiants;
    private javax.swing.JButton btn_mat_estudiant;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
